### ISSUE TITLE
JCE cannot authenticate the provider KALKAN

### ISSUE THREAD

**Issue by MargulanDev** [malikzh/NCANode#153]
получаю ошибку при попытке подписания xml [версия 3.2.2]

java.io.IOException: error constructing MAC: java.lang.SecurityException: JCE cannot authenticate the provider KALKAN
at kz.gov.pki.kalkan.jce.provider.JDKPKCS12KeyStore.engineLoad(JDKPKCS12KeyStore.java:634) ~[kalkancrypt-0.7.2.jar!/:0.7.2]
at java.base/java.security.KeyStore.load(KeyStore.java:1473) ~[na:na]
at kz.ncanode.wrapper.KalkanWrapper.read(KalkanWrapper.java:61) ~[classes!/:na]
at kz.ncanode.wrapper.KalkanWrapper.tryReadKey(KalkanWrapper.java:110) ~[classes!/:na]
at kz.ncanode.wrapper.KalkanWrapper.lambda$read$0(KalkanWrapper.java:95) ~[classes!/:na]
at java.base/java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180) ~[na:na]

**Comment by FlatronBuda** [comment]
У меня Тоже возникает данная. Что странно если запускать то выходит данная ошибка java -jar .\NCANode.jar
`{
    "status": 400,
    "message": "Key reading error: Unknown error. Please see logs."
}`

Но если запускаю из среды разработки IntelliJ IDEA 2022.3.2 все работает без проблем. Странно.
Версия Java 17.0.6

**Comment by MargulanDev** [comment]
У вас не macos? У меня была проблема когда запускал на маке, потом с виндовс все заработала.

**Comment by FlatronBuda** [comment]
После гугления набрел на [Ошибка при подписании новыми библиотеками на JAVA 7](https://forum.pki.gov.kz/t/oshibka-pri-podpisanii-novymi-bibliotekami-na-java-7/1662)
ну и еще подтверждение [JCE cannot authenticate the provider BC [windows]](https://stackoverflow.com/questions/69383210/jce-cannot-authenticate-the-provider-bc-windows)

[Скачал этот дистрибутив там под все версии OS](https://adoptium.net/temurin/releases/?version=17) 
и заработало)

На всякий случай версия JAVA
Windows 10 в терминале набрал команду java --version
openjdk 17.0.6 2023-01-17
OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10)
OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (build 17.0.6+10, mixed mode, sharing)
