### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by GHostlyFOX** [malikzh/NCANode#202]
CentOS Stream release 9
crl enabled: true

```
2024-11-26 10:33:32.211 ERROR 16402 --- [o-14574-exec-37] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.OutOfMemoryError: Java heap space] with root cause

java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.Arrays.copyOfRange(Arrays.java:3822) ~[na:na]
        at java.base/sun.security.util.DerInputStream.toByteArray(DerInputStream.java:96) ~[na:na]
        at java.base/sun.security.x509.X500Name.parseDER(X500Name.java:777) ~[na:na]
        at java.base/sun.security.x509.X500Name.<init>(X500Name.java:307) ~[na:na]
        at java.base/sun.security.x509.X509CRLImpl.parse(X509CRLImpl.java:1121) ~[na:na]
        at java.base/sun.security.x509.X509CRLImpl.<init>(X509CRLImpl.java:136) ~[na:na]
        at java.base/sun.security.provider.X509Factory.engineGenerateCRL(X509Factory.java:395) ~[na:na]
        at java.base/java.security.cert.CertificateFactory.generateCRL(CertificateFactory.java:513) ~[na:na]
        at kz.ncanode.service.CrlService.loadCrl(CrlService.java:176) ~[classes!/:na]
        at kz.ncanode.service.CrlService.verify(CrlService.java:96) ~[classes!/:na]
        at kz.ncanode.service.CertificateService.attachValidationData(CertificateService.java:34) ~[classes!/:na]
        at kz.ncanode.service.CmsService.verify(CmsService.java:239) ~[classes!/:na]
        at kz.ncanode.controller.CmsController.verify(CmsController.java:37) ~[classes!/:na]
        at jdk.internal.reflect.GeneratedMethodAccessor55.invoke(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.22.jar!/:5.3.22]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-5.3.22.jar!/:5.3.22]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-5.3.22.jar!/:5.3.22]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.22.jar!/:5.3.22]        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.22.jar!/:5.3.22]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.22.jar!/:5.3.22]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1070) ~[spring-webmvc-5.3.22.jar!/:5.3.22]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) ~[spring-webmvc-5.3.22.jar!/:5.3.22]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.22.jar!/:5.3.22]
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.3.22.jar!/:5.3.22]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:681) ~[tomcat-embed-core-9.0.65.jar!/:na]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.22.jar!/:5.3.22]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[tomcat-embed-core-9.0.65.jar!/:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat-embed-core-9.0.65.jar!/:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.65.jar!/:na]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.65.jar!/:na]
```

**Comment by GHostlyFOX** [comment]
Или подскажите как NCANode-3.3.2.jar выделить больше памяти?
в самой ОС памяти свободной хватает

**Comment by eudj1n** [comment]
@GHostlyFOX добавьте параметры `Xms` и `Xmx`:

```
ExecStart=/bin/java -Xms2048m -Xmx4096m -jar NCANode-3.3.2.jar
```
