### ISSUE TITLE
Ошибка при проверке подписи

### ISSUE THREAD

**Issue by NigmetovTimur** [malikzh/NCANode#91]
Добрый день. В чем может быть причина ошибки? Начала появляться дня два назад. До этого было норм.
NCANode v2.3.0

java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at kz.ncanode.api.core.ApiController.invokeMethod(ApiController.java:67)
	at kz.ncanode.api.core.ApiController.callMethod(ApiController.java:39)
	at kz.ncanode.api.version.v20.ApiVersion20.process(ApiVersion20.java:99)
	at kz.ncanode.api.ApiServiceProvider.process(ApiServiceProvider.java:96)
	at kz.ncanode.interaction.interactors.HttpInteractor$HttpApiHandler.handle(HttpInteractor.java:99)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
	at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:692)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:664)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$DefaultExecutor.execute(ServerImpl.java:159)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:442)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:408)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: kz.ncanode.api.exceptions.ApiErrorException: Connection timed out (Connection timed out)
	at kz.ncanode.api.version.v20.controllers.InfoController.pkcs12(InfoController.java:92)
	... 19 more

**Comment by malikzh** [comment]
Добрый день. Вероятно не может достучаться до ocsp сервера, либо, если это
при запуске, то не может скачать crl. Проверьте настройки NCANode.ini.

вт, 15 июн. 2021 г., 11:49 Electric ***@***.***>:

**Comment by malikzh** [comment]
.....................................

Malik приглашает поддерживать связь в LinkedIn.

Malik Zharykov
Senior Engineer Software
Казахстан

См. профиль https://www.linkedin.com/comm/in/malik-zharykov-bba687165?trk=eml-guest-invite-pprofile-link-cta&trkEmail=eml-email_m2g_invite_single_01-null-373-null-null-%7E5o2nr7%7Eksj1p9dd%7Eyp-null-neptune%2Fprofile%7Evanity%2Eview&lipi=urn%3Ali%3Apage%3Aemail_email_m2g_invite_single_01%3B%2FH9IJcWPRqWjHIRLz0fNfQ%3D%3D

Подтвердите, что Вы знакомы с участником Malik https://www.linkedin.com/e/v2?e=-5o2nr7-ksj1p9dd-yp&lipi=urn%3Ali%3Apage%3Aemail_email_m2g_invite_single_01%3B%2FH9IJcWPRqWjHIRLz0fNfQ%3D%3D&t=suwj&tracking=eml-guest-invite-cta&ek=email_m2g_invite_single_01&validationToken=wgtaMwbD&invitationId=6834135478158077952


.....................................

Отменить подписку: https://www.linkedin.com/e/v2?e=-5o2nr7-ksj1p9dd-yp&t=lun&midToken=AQFmrFVhGEd36Q&ek=email_m2g_invite_single_01&li=381&m=unsub&ts=unsub&loid=AQFCpgBSuA1fjQAAAXte6IzFj41F-K_YbssUgM7FUXrmOKm_AtJOWPEvUvUiUc8jbeldTDU6GloxzUky7MDqX8G6Y2fFmOXALP3dxP2k4Dqtsqd7T49t0K05rDr7Bqy9cOZcUsdL3SSQj8KbMDY1XGvTAS5lBC4Z9Q&eid=-5o2nr7-ksj1p9dd-yp

Справка: https://www.linkedin.com/e/v2?e=-5o2nr7-ksj1p9dd-yp&lipi=urn%3Ali%3Apage%3Aemail_email_m2g_invite_single_01%3B%2FH9IJcWPRqWjHIRLz0fNfQ%3D%3D&a=customerServiceUrl&ek=email_m2g_invite_single_01&li=380&m=footer&ts=help&articleId=67


Вы получаете рассылку «Приглашение» по эл. почте. LinkedIn будет использовать Ваш адрес эл. почты, чтобы предоставлять советы Вам и другим участникам, например в модуле «Люди, которых Вы можете знать».

Это сообщение было отправлено на адрес ***@***.***

© 2021 LinkedIn Ireland Unlimited Company, Wilton Plaza, Wilton Place, Dublin 2. LinkedIn является зарегистрированным фирменным наименованием LinkedIn Ireland Unlimited Company. LinkedIn и эмблема LinkedIn являются товарными знаками компании LinkedIn.
